package com.smartcampus.model;

public enum NotificationType {
    BOOKING_APPROVED, BOOKING_REJECTED, BOOKING_CANCELLED,
    TICKET_STATUS_CHANGED, TICKET_ASSIGNED, TICKET_COMMENTED,
    COMMENT_ON_YOUR_TICKET, COMMENT_ON_YOUR_BOOKING,
    SYSTEM_ALERT
}
