spring:
  application:
    name: pafdb
  
  data:
    mongodb:
      uri: mongodb+srv://waruna:waruna@pafdb.2676cf5.mongodb.net/?appName=pafdb
      # Alternative configuration (if not using URI):
      # host: localhost
      # port: 27017
      database: pafdb
      # username: root (if authentication is enabled)
      # password: root
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:726925929549-olu77b1316hcc6piav552n3til34iefn.apps.googleusercontent.com}
            client-secret: ${GOOGLE_CLIENT_SECRET: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}
            redirect-uri: http://localhost:8080/api/login/oauth2/code/google
            scope: profile,email
        provider:
          google:
            user-name-attribute: sub

server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    root: INFO
    com.smartcampus: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

app:
  jwt:
    secret: ${JWT_SECRET:z6568962657d483c65c6c6d56686a63586b65646351666c56616462635c656162}
    expiration: 86400000
  file:
    upload-dir: uploads/
